    <div class="artikel-lain">
    <img src="images/Rectangle 12 (9).png">
    <div class="text-lain">
        <p class="heading-lain">Pelaksanaan ASAS 2023, Manfaat Ujian Akhir bagi Siswa</p>
    <p>[ #kritisaga ] Haloo fiver`s, Desember ini siswa siswi beserta Bapak Ibu guru SMPN 5 Malang disibuk untuk pelaksanaan ASAS ganjil 2023. Asas merupakan akronim dari Assesment sumatif akhir semester, yang dilaksanakan untuk siswa semester 1, 3 dan 5. Asas kali ini dilaksanakan berbeda dengan ujian senester sebelumnya karena dilaksanakan semua angkatan secara bersama-sama. Meskipun bersama semua, tempat duduk peserta di buat acak antara campuran dari 2 angkatan untuk menghindari hal-hal yang tidak diinginkan. Untuk itu, panitia Asas menyipakn kegiatan ini dengan matang-matang seminggu sebelum kegiatan dilaksanakan. Nama siswa dan pengumuman ditempelkan setelah pelaksanaan kerja bhakti disemua kelas.</p>
    <p>Pada tanggal 4 Desember hingga 11 Desember anak-anak melaksanakan Asas sesuai ketentuan dan peraturan yang telah disampaikan oleh panitia. Pelaksanaan pengerjaan ujian yakni secara daring melalui aplikasi Thatquis dan beberapa juga menggunakan Google form. Bagi siswa yang memiliki kendala karena perangkat maupun paket internet, sekolah menfasilitasi mereka dengan menggunakan laboratorium komputer dengan sebelumnya mendapat izin walikelas. Alhamdulillah pelaksanaan Asas berlangsung dengan lancar, beberapa siswa yang tidak mampu hadir bisa melaksanakan ujian susulan dan remidi pada pekan berikutnya ditanggal 12 hingga 14 Desember 2023.</p>
        <p>Asas ini tentunya penting bagi siswa siswi, berikut ini manfaat dari ujian yakni :</p>
        <ol>
            <li>Menghargai pentingnya waktu. Siswa yang akan melaksanakan ujian harus mengetahui waktu kapan jadwal ujian akan dilaksanakan. Siswa harus meluangkan waktu untuk belajar malam, belajar kelompok, belajar di rumah, atau bahkan meminta waktu kepada gurunya untuk bimbel. Saat pelaksanaan ulangan jangan sampai terlambat datang ke kelas untuk ujian.</li>
            <li>Memahami arti pentingnya belajar. Melalui ulangan, apabila siswa ingin memperoleh nilai baik maka harus belajar. Jika tidak belajar dapat dipastikan tidak naik kelas. Materi-materi yang dipelajari apabila keluar saat ulangan akan menjadi kebahagiaan tersendiri bagi siswa dan ada rasa bangga bahwa mendapatkan nilai tinggi.</li>
            <li>Melatih kejujuran, ujian melatih kejujuran pada siswa, saat ulangan siswa harus mengerjakan sendiri soal-soal dari hasil belajar yang sudah dilakukan. Apabila sudah terbiasa dapat diterapkan pada kehidupannya yang lain.</li>
            <li>Menghargai hasil dan mengukur usaha, apapun hasil ujiannya maka ia harus menerimanya. Nilai rendah atau tinggi itu merupakan hasil usaha setelah belajar. Jika hasil ujian dirasa kurang, maka akan menjadi refleksi untuk perbaikan dan semangat belajar di semseter berikutnya.</li>
            <li>Semangat juang, melalui ujian siswa dituntut memiliki semangat juang yang gigih untuk hasil belajar maksimal. Ikhtiar maksimal hasilnya mendekati akan harapan.</li>
            <li>Untuk memotivasi diri. Diadakannya suatu ulangan adalah sebagai motivasi diri bagi masing-masing pelajar untuk lebih meningkatkan prestasinya. Semua individu pasti ingin lulus ujian dan bahkan ingin mempunyai nilai yang bagus, tapi untuk memperoleh itu semua tidaklah semudah kita hanya menghayal atau bermimpi saja. Tetapi bukan berarti pula prosesnya juga sulit untuk mencapainya. Jika kita ingin hasil yang bagus maka kita juga harus melakukannya dengan cara yang bagus pula, jangan melakukannya dengan cara setengah hati apalagi dengan cara yang curang.</li>
        </ol>
    </div>
    </div>